name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    inputs:
      run_slow_tests:
        description: 'Run slow tests'
        required: false
        default: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        pytest test_microstate_validation.py -v -m "not slow"
    
    - name: Run slow tests
      run: |
        pytest test_microstate_validation.py -v -m "slow"
      if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event.inputs.run_slow_tests == 'true'
